fluttercommunity/flutter_downloader

- android/src/main/java/vn/hunghd/flutterdownloader/IntentUtils.java
APK file open in intent was not working for android 6.0 or earlier version of Android.
> APK was not opening in SDK < 24.

- example/lib/main.dart
- ios/Classes/FlutterDownloaderPlugin.m
Fix issue [#32](https://github.com/fluttercommunity/flutter_downloader/issues/32)
> escape quotes from sql

- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
> Fix the uncompatibility with background regestration context

- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
> Fixed android registerCallback exception (#153)

- README.md
Added not condition for registering plugin on iOS
> Added not condition for registering plugin

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
There is rfc for unicode filenames in content-disposition, using `filename*=utf-8''"имя файла.png"` header: https://tools.ietf.org/html/rfc5987
And also file names which getting from url (if there is no content-disposition) can be url decoded.
> Handle unicode filenames in content-disposition (filename*=) and in urls

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/lib/main.dart
- example/pubspec.yaml
👉 This PR to help:
- Resolve download issue with [ScopedStorage](https://developer.android.com/about/versions/11/privacy/storage)
- [PackageVisibility](https://developer.android.com/about/versions/11/privacy/package-visibility) with Android 11 (In Android 11, can not open downloaded file from notification)
- Upgrade `compileSdkVersion` and `targetSdkVersion` to 30 ([policy update](https://developer.android.com/distribute/play-policies) from Google Play)
👉 Reference opened issue (This PR may help these issues):
#503 
#498 
#492 
#488 
#330 
👉 Demo:
https://user-images.githubusercontent.com/29337364/132326529-05f2eb2f-1158-4f39-8043-eadde2632859.mp4
> Upgrade to support Android SDK 30

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadTask.java
- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskContract.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskDao.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskDbHelper.java
- lib/src/downloader.dart
👉 This PR to help:
Hot fix the mistake from PR #522 
👉 Reference opened issue: 
#525 
👉 Demo:
https://user-images.githubusercontent.com/29337364/132745099-bb6cabf5-f5c3-42f5-82b5-a5ee40b1800a.mp4
> Hotfix: file is not saved on savedDir

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
Allows download URL that have 307 or 308 redirection on android
Closes #88
> Allows download URL that have 307 or 308 redirection on android

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
- lib/src/downloader.dart
some time we need  ignore ssl error to test server,so i want add this  parameter
> Android  add ignoreSsl

- README.md
Added important "ignoreSsl" description.
> Update README.md - ignoreSsl description

- .github/workflows/test.yaml
- CHANGELOG.md
- example/lib/main.dart
- lib/src/downloader.dart
- pubspec.yaml
@hnvn should fix GitHub Action
> Prepare for version 1.8.0

- ios/Classes/FlutterDownloaderPlugin.m
Added try-catch blocks to the taskDictFromRecordArray method for iOS to catch any NSRangeException. If some columns don't match with the ones in the DB then the app will crash. There are cases where the `headers` column is not found causing the app to crash. Only happened in production and cannot be reproducible locally. 
This will fix issue: https://github.com/fluttercommunity/flutter_downloader/issues/218
> fix for [iOS] NSRangeException from taskDictFromRecordArray method

- example/lib/home_page.dart
- ios/Classes/FlutterDownloaderPlugin.m
Some minor updates from suggestions in https://github.com/fluttercommunity/flutter_downloader/pull/678
> update exit button in example app, minor coding style fixes

- CHANGELOG.md
- pubspec.yaml
This PR:
- Improves changelogs, mainly for v1.8.1
- Sets package version to 1.8.2 🎉
> Release version 1.8.2

- CHANGELOG.md
- README.md
- android/src/main/java/vn/hunghd/flutterdownloader/DownloadTask.java
- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskContract.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskDao.java
- android/src/main/java/vn/hunghd/flutterdownloader/TaskDbHelper.java
- lib/src/downloader.dart
- pubspec.yaml
This reverts #437.
Fixes #705, unfortunately post-factum.
> Revert "Ability to display custom notification title on Android (#437)"

- README.md
Add comma in FlutterDownloader initialize section
> Add comma in FlutterDownloader initialize section

- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadTask.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDao.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDbHelper.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskEntry.kt
- lib/src/downloader.dart
- lib/src/models.dart
+ Add `allowCellular` flag to Dart and default 
+ Add flag to Android code and pass it to the `WorkManager`
+ Migrate the database on Android
> Add option to download only on wifi

- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt
> Check protocol when opening connection without ignoreSsl

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> Set Kotlin JVM target to 1.8

- CHANGELOG.md
- pubspec.yaml
> bump version to 1.11.1

- android/build.gradle
- example/android/app/build.gradle
Hi Salma!
This is a tiny change. See https://github.com/flutter/flutter/issues/63533#issuecomment-2027851231 for rationale
> Bump Android compileSdk to 34
