- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
- lib/flutter_downloader.dart
we came across an issue where an android user would not be able to pull data from our servers when they were low on memory. The buildRequest function was updated to take a boolean that we can pass that will allow a user to download when memory is low. The default value is set to true so that it acts the way it did before adding the change
> overriding setRequiresStorageNotLow

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
- android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
- android/src/main/java/vn/hunghd/flutterdownloader/IntentUtils.java
**1. merge `getOpenFileIntent` and `validateIntent` to `validatedFileIntent`**
when to comsume it,check the returning Indent is not null then run `startAcitvity(validatedFileIntent)`      
2.In `validatedFileIntent` method,     
if original contentType fails `validateIntent`, use `URLConnection.guessContentTypeFromStream`(inputFile) && `URLConnection.guessContentTypeFromName(path)` to get workable `mimeType`
> fix apk file open fails in some cases

- lib/src/downloader.dart
Add an assert checking that `FlutterDownloader.initialize()` is not called more than once, because that may end up registering plugins multiple times and crashing the app.
Related to #154.
> Initialize() should not be called more than once

- example/lib/main.dart
The path separator used by the operating system to separate components in file paths.
From the [docs](https://api.dart.dev/stable/2.7.0/dart-io/Platform/pathSeparator.html)
> Updated constant path separator in Flutter example

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
Fixes issue #228
Ensure the native Android initialization process is started before calling FlutterMain.ensureInitializationComplete. During testing it was discovered in certain circumstances this was not the case and the app would crash. Call the initialization multiple times does nothing.
See docs:
[https://api.flutter.dev/javadoc/io/flutter/view/FlutterMain.html#startInitialization-android.content.Context-](https://api.flutter.dev/javadoc/io/flutter/view/FlutterMain.html#startInitialization-android.content.Context-)
[https://github.com/flutter/engine/blob/9acec4102a3536e41287704d33640dc8ff54e67f/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java](https://github.com/flutter/engine/blob/9acec4102a3536e41287704d33640dc8ff54e67f/shell/platform/android/io/flutter/em …
> Ensures native system is initialized. Android only.

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
Currently, there are only two HTTP codes considered as redirect codes, but we have HTTP 303 `SEE OTHER` in addition to them. Without it the downloader cancels the request.
> Add HTTP 303 to redirect group

- ios/Classes/FlutterDownloaderPlugin.m
If the plugin is singleton and use this plugin from 2 or more isolates, it causes MisiingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader).
Android plugin is already not singleton due to flutter android v2 embedding.
> To support use from isolation, do not use singleton. (iOS)

- ios/Classes/FlutterDownloaderPlugin.m
Pull request for three changes, one critical:
1) fix removeMethodCall: currently the sqlite database can get polluted with ENQUEUED and RUNNING tasks that can never be removed (see commit for details)
2) made currentTimeInMilliseconds a long long instead of a long (supposed to be)
3) addressed a couple of compiler warnings
> Critical fix to removeMethodCall

- lib/src/models.dart
I didn't think it was so clear what updateTime was. I figured it was either seconds or milliseconds since unix epoch, but wasn't sure which, and it makes a difference.
The implementation uses java.lang.System.currentTimeMillis(), which returns milliseconds since epoch, so I updated docs accordingly
> Document exactly what update time is

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
I have files that are redirect multiple url.
If it is redirect less than 2 times, everything works fine.
But if it is redirect more than 2 times, redirected url since the 3rd time will be incorrect.
`base` url we use was the original url (`fileUrl`) so at the 3rd time redirection which it should use the 2nd URL but it still use original URL.
Use `url` instead of `fileUrl` when assigning to `base`
> Fix wrong base URL on Redirect multiple url

- android/gradle.properties
For AndroidX support there need to be two additional lines in the gradle.properties. I have added them. Please accept this PR
> Update gradle.properties to enable androidX support

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
Use case: 
on Android, When app is force quit and restarted work is rescheduled,  so the work is in running state again but starts with 0% abandoning the partially downloaded file.
see this for reference:
https://stackoverflow.com/questions/50682061/android-is-workmanager-running-when-app-is-closed
_App info "Force stop":
Work stops, will only continue when app is started again_
so there needs a way to resume partially downloaded files.
> Add automatic resume for unexpectedly killed works.

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
When the getContentLengthLong was implemented it started to break Android < 7 because this method does not exist!
This hotfix should be Merge ASAP as the plugin is not working on Android < 7.
This fixes  at least:
#458 #440 #434
> fix getContentLength for Android < 7

- ios/Classes/FlutterDownloaderPlugin.m
fix shortenSavedDirPath method when substringWithRange return nil concatenated a null on the path and returned not found path.
Platform: IOS
> Fix shortenSavedDirPath method iOS

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
fix bug: when call  FlutterDownloader.open on downloadCallback,it will throw "only success task can be opened" exception, due to it "updateNotification " first then excute "taskDao.updateTask"
> fix "only success task can be opened" bug

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
Android processes a limited number of worker threads at the same time. For enqueued tasks that get cancelled through `cancel`, it may take a long time for their status to change to `cancelled` and for the progress update to arrive.
This PR fixes it by leveraging the [`onStopped` callback](https://developer.android.com/reference/androidx/work/ListenableWorker#onStopped()) to cancel a task that is in the enqueued state immediately. Also, tasks that are cancelled (or even have been removed entirely) will not be processed in `doWork` anymore to avoid any further processing or exceptions.
> (Android) Add onStopped to cancel enqueued tasks earlier

- android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java
> Fix lookupCallback crash

- README.md
- lib/src/callback_dispatcher.dart
Need to add `@pragma('vm:entry-point')` to callbackDispatcher & custom callback for these to be triggered properly in release mode for Android. The issue only started happening after upgrading to flutter 2.10. 
This PR will fix this issue https://github.com/fluttercommunity/flutter_downloader/issues/614
For more info about pragma entry-point, check out:
https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
https://github.com/flutter/flutter/wiki/Experimental:-Launch-Flutter-with-non-main-entrypoint#avoid-tree-shaking-in-release
> fix callbackDispatcher not found issue in release mode for Android

- ios/Classes/FlutterDownloaderPlugin.m
On iOS, when a running or enqueued task is deleting，it may be executed concurrently on main thread and thread that database queue `vn.hunghd.flutter_downloader` dispatched，it may cause that `executeQueryResults` returns non `SQLITE_DONE(101)` in code ` int executeQueryResults = sqlite3_step(compiledStatement)`，finally, failed, the task is not removed from database actually.
For example, 12 tasks try to be removed in a for loop, but only 9 tasks are SQLITE_DONE.
￼
I'm not sure if there's the case in other code, I haven't come across it yet.
> on iOS, bug fixed when deleting task concurrently

- ios/Classes/FlutterDownloaderPlugin.m
Problem:
I observed that when downloading an `invalid` resource, it returns a success in [URLSession: downloadTask: didFinishDownloadingToURL:], then it returns a failure in [URLSession: task: didCompleteWithError:], finally callback twice. The expectation should be to only return a failure.
Why:
1. In [URLSession: downloadTask: didFinishDownloadingToURL:] , the http status code of the invalid resource's downloadTask is 404 or other failed code, and the location exists invalid temporary file which will be copied to the destinationURL. The copy result is succeeded, so it returns a success.
2. In [URLSession: task: didCompleteWithError:], invalid resource task status code is also 404 or other failed code, so it returns a failure.
Solution:
When 404  or other failed http status code appears, …
> fix: on iOS, check http status when downloaded finished

- .github/workflows/test.yaml
- analysis_options.yaml
- lib/flutter_downloader.dart
- lib/src/callback_dispatcher.dart
- lib/src/downloader.dart
- lib/src/models.dart
- pubspec.yaml
A bunch of smaller refactors
- formatted all code using `flutter format`
- added linting using [flutter_lints](https://pub.dev/packages/flutter_lints)
- added a GitHub Action which runs `flutter format` and `flutter analyze` for Pull Requests. This will require new code to conform to a single style
- if `FlutterDownloader.initialize(debug: false)` is called, then no logs will be printed to the console (at least on the Dart side).
I also rewrote most of the docs. I strived for conformance with [Effective Dart guide](https://dart.dev/guides/language/effective-dart/documentation).
@hnvn, please review if you have some free time :)
> Log only when `debug` is true + clean up documentation

- android/src/main/java/vn/hunghd/flutterdownloader/TaskDbHelper.java
Currently, the database is just deleted when migrating. This can be pretty confusing when upgrading flutter_downloader, and may cause issues in apps that depend on the database always being there. This PR adds a simple migration from version 2 to 3 so that the database is upgraded instead of deleted.
> Add SQLite migration from version 2 to 3

- README.md
I wish someone included this in the readme earlier. My flutter guy was saying it wasn't possible to pass auth token with the download URL and I had to dig up the code to check if it was possible. And viola!
P.S I have no understanding of flutter/dart.
> chore(readme): add header parameter to enqueue function

- lib/src/models.dart
As discussed in https://github.com/flutter/flutter/issues/109248
this fixes #698 
As the app crashes on release mode in flutter 3.3+  and it is not a breaking change i suggest releasing a new version ASAP
> Add vm-entry to model

- CHANGELOG.md
- lib/src/downloader.dart
- pubspec.yaml
> fix `FlutterDownloader.open()` always returning false

- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt
If `if clause(if ((responseCode...)` was never executed, the `lastProgress` is always `0`. It will storage a wrong progress(`0`). So `lastProgress` needs assign the real initial value to avoid the `0-case`.
In fact, this happened indeed when I was developing. While I switch action such as pause/resume frequently in poor network, the progress will flash between `0` and real progress on the UI.
For further reason, `isStopped` is always `true` so that `if clause(if ((responseCode...)` was never executed. I guess that it's due to workers over the limit.
> fix: android wrong last progress due to missing initial value

- android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/IntentUtils.kt
- example/android/app/src/main/AndroidManifest.xml
- example/lib/home_page.dart
- example/pubspec.yaml
- example app: simplify permission code
- code refactors
- remove not-needed requestLegacyExternalStorage from Manifest
- add "save to public storage" checkbox to example app
- clean up example app home page code
> Clean up example app code

- ios/Classes/DBManager.m
PR #728 suggested to had database file migration on iOS from the documents directory to the application support directory on init.
On launch, now check if the DB file exists in the app directory.
If not, search on the document directory and move it.
If not on the document directory, copy DB file from Assets
> Handle migration for PR #728

- lib/src/downloader.dart
There's an issue on following line:
https://github.com/fluttercommunity/flutter_downloader/blob/cc62a526119266e83c825f11b20c0dc00ea9ebd5/lib/src/downloader.dart#L165
Here's the crash log:
```
flutter: |>|> download-manager initializing DownloaderDataSource
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'bool' in type cast
#0      FlutterDownloader.loadTasks.<anonymous closure> (package:flutter_downloader/src/downloader.dart:165:51)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of …
```
> [iOS] fix crash when allow_cellular is null on iOS

- ios/Classes/DBManager.m
+ Use the correct data type to evaluate the error codes when
opening the SQLite database.
As mentioned in #757, I noticed some issues with the DB handling. I was trying to add code to migrate the database schema to allow adding new columns to the database, when I noticed that the new copying mechanism didn't work properly.
I don't quite understand why, but checking if the file exists at the new location always returns ` false` and the plugin attempts to copy the file again.
In some of my tests the copy then failed because the file already existed at that location.
But this is not even the main part of the problem. The actual problem is, that you never find out about this, because everything just silently fails.
I fixed the handling of the SQLite error codes in this PR, which should now …
> Correctly read the error/success codes

- lib/src/downloader.dart
In the last update #774 was added the allowCellular default value, but only for the loadTasks function, it is needed also for loadTasksWithRawQuery (issue related: #786 )
> Fix allow_cellular error in iOS for loadTasksWithRawQuery

- example/lib/home_page.dart
FlutterDownloader example does not work on some latest Flutter SDK versions. Sending message by [int] on port will resolve the issue.
Related issues:
https://github.com/fluttercommunity/flutter_downloader/issues/808
https://github.com/fluttercommunity/flutter_downloader/issues/804
> fix: send message by [int] on port in Example

- lib/src/downloader.dart
Calling UI function on Downloader Framework is non-standard, and it makes difficult to program in background isolation.
Better yet, call it outside the framework by user.
Related issue https://github.com/fluttercommunity/flutter_downloader/issues/809
> remove that call [WidgetsFlutterBinding.ensureInitialized] in [initialize]

- ios/Classes/DBManager.m
An error occurred getting the database file,  because the application support directory that stored the database file does not exist.
The directory could be created by this function [[URLForDirectory:inDomain:appropriateForURL:create:error:]](https://developer.apple.com/documentation/foundation/nsfilemanager/1407693-urlfordirectory/) lazily.
Related issues:
https://github.com/fluttercommunity/flutter_downloader/issues/786
https://github.com/fluttercommunity/flutter_downloader/issues/787
https://github.com/fluttercommunity/flutter_downloader/issues/814
> fix: Create the application support directory if it does not already exist

- ios/Classes/FlutterDownloaderPlugin.m
`CountOfBytesReceived` is unreliable. Data inconsistency occurred.
We'd better manage the progress by `task map` and function `[URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]`
> fix: iOS apply tasks progress instead of computed progress on pause

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
This fixes Android build when using AGP v8.
> Add namespace to `android/build.gradle`

- android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt
When delete() was called, the plugin first tried to remove the file using MediaStore, and then was (trying to) fall back to normal File#delete(). Unfortunately, the calls to MediaStore were throwing a SecurityException, so the fall-back code was never executed.
This PR:
- fixes #413 
- fixes #496 
- fixes #773 (which was closed because OP found a workaround)
> Fix delete() not falling back to normal File#delete()

- lib/src/callback_dispatcher.dart
> Don't crash when `FlutterDownloader.registerCallback()` wasn't called

- ios/Classes/FlutterDownloaderDBManager.h
- ios/Classes/FlutterDownloaderDBManager.m
- ios/Classes/FlutterDownloaderPlugin.m
Hello!
I'm submitting this PR to address a public naming conflict of `DBManager` that is also being used in the PrivateFramework for CallHistory on iOS.   This PR contains no logic changes other than the simple renaming of `DBManager` to `FlutterDownloaderDBManager`.
Thank you for contribution to the Flutter Community!  Please let me know if you have any questions or requests regarding this Pull Request.
> Rename DBManager to resolve name conflict with CallHistory private framework

- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadTask.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt
- android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDao.kt
On Android when source had null content-type, the request fails and throws exception. It's unexpected behavior since there is nothing wrong with downloaded file.
Proposing to resolve https://github.com/fluttercommunity/flutter_downloader/issues/935 and https://github.com/fluttercommunity/flutter_downloader/issues/936
> feat: allow nullable content-type

- README.md
Hello! Thanks for creating such an awesome package!
It's incredible that it supports not only downloads but also local DB storage and viewing.
I noticed a few outdated sections in the documentation, so I made some corrections.
`version: ^1.11.8`
- Fixed what needs to be defined before the `savedDir` parameter. 
- Fixed DownloadTaskStatus function.
- Fixed SendPort Optional.
- Fixed explicit loadTasks function's type
Once again, Thank you for this amazing library!
> Made a few edits to the Android-related explanations in the README.md
